name: CI
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-24.04, macos-14, macos-13, windows-11-arm, windows-2025]
        version: [master, 0.15.1, 0.14.1, 0.14.0]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{matrix.version}}
      - run: echo "OS=$(uname -s), ARCH=$(uname -m), RUNNER=${{matrix.os}}"
      - run: zig version
      - run: zig env
      - run: zig build check test --summary all
  lint:
    name: Check Format and Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: latest
      - uses: crate-ci/typos@master
        with:
          files: ./
      - run: zig fmt --check .
