name: Test using various zig versions, operating systems, and architectures
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-26, windows-2025]
        version: [master, 0.16.0, 0.15.2, 0.14.1]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{matrix.version}}
      - run: echo "OS=$(uname -s), ARCH=$(uname -m), RUNNER=${{matrix.os}}"
      - run: zig version
      - run: zig env
      - run: zig build --summary all
      - run: zig build test --summary all
